### ISSUE TITLE
Warning message from `broadcast-channel/dist/es/method-chooser.js`

### ISSUE THREAD

**Issue by mila1808** [pubkey/broadcast-channel#311]
**"broadcast-channel": "^3.1.0"**

`Invalid import. Should recieve a string. node_modules/broadcast-channel/dist/es/method-chooser.js`

**Comment by pubkey** [comment]
I have no chance to reproduce this with that little information.
Please debug into it and check if you can find the root problem.

**Comment by jpike88** [comment]
the problem is that the bundler we are using (```fuse-box```) is throwing a warning on this line:

https://github.com/pubkey/broadcast-channel/blob/2232db505ca3f6dc312e00a977981a97ad5380ab/src/method-chooser.js#L27

We're collaborating with the maintainer @nchanged to figure out a way forward. The problem appears to be that this code is kind of hacky and for bundlers that are smart or thorough enough to try and resolve all requires they see, it will cause an issue. Thankfully it's just throwing a warning and not breaking builds.
