### ISSUE TITLE
Question: What is the safest way to use this with sensitive data?

### ISSUE THREAD

**Issue by rowrowrowrow** [pubkey/broadcast-channel#34]
Thanks for the great contribution!

I'd like to use this for sharing some sensitive and non-sensitive data between tabs. In what way would it be secure to use this with sensitive data? Mainly thinking about if the browser doesn't doesn't support the BroadcastChannel API and this fallsback to IndexedDB or LocalStorage.

Best!!!

**Comment by pubkey** [comment]
Broadcasting sensitive data is dangerous because localstorage and idb can keep it stored for longer then the tab is open.
You can encrypt the data before sending it which is what I do at RxDB where also sensitive data is send over the broadcast-channel.

However you somehow have to share a password or use asynchronous encryption.

**Comment by rowrowrowrow** [comment]
Thanks for the quick response, are you at all able to share any more info on your encryption workflow for this?

My take right now is that if the BroadcastChannel API is available then sending sensitive data is ok, if not exclude the sensitive data. Does that make sense?

**Comment by pubkey** [comment]
Yes. Sending data over the BroadcastChannel API is safe because it will not be stored on the file system.

**Comment by pubkey** [comment]
I'm closing this. I do not think this should be solved in this module.

**Comment by rowrowrowrow** [comment]
Thanks for your input
