### ISSUE TITLE
IndexedDB restricted in cross-origin iframes in Safari

### ISSUE THREAD

**Issue by ChuanfengZhang** [pubkey/broadcast-channel#36]
Hey there
We get errors about IndexedDB in Safari as well as Mobile Safari but only when using iFrames.

> SecurityError: IDBFactory.open() called in an invalid security context

![image](https://user-images.githubusercontent.com/18238800/67269364-2f527080-f4e9-11e9-8ffd-8f4270a731e6.png)

**Comment by pubkey** [comment]
I think this is an edge case.
Also the proposed fix would be confusing because only inside of the iframe the localstorage-method would be chosen will outside of it, the idb-method is still there.

I think if you want to use this module inside of a thrid-party-origin iframe, you should hardly set the method when constructing the broadcast channel.

Maybe we should wrap the error and give the user a link to why this is not working inside of cross-origin iframes in safari
