### ISSUE TITLE
Remaining `require` statements in ESM version

### ISSUE THREAD

**Issue by benmccann** [pubkey/broadcast-channel#690]
## Case
Bug / packaging issue

## Issue
Unfortunately, even with the latest, I'm still having trouble using `broadcast-channel` with Vite / SvelteKit. There are a couple issues that I've discovered:

https://github.com/pubkey/broadcast-channel/blob/1e905f1183585ba3be6fa9f771a4eaf0616185df/src/method-chooser.js#L6 loads https://github.com/pubkey/broadcast-channel/blob/master/src/methods/node.js which uses `require` instead of `import`

https://github.com/pubkey/broadcast-channel/blob/master/src/methods/node.js loads a couple files from `../../dist/lib` which also are not ESM 

## Info
  - Environment: Node and browser 
  - Method: Node
  - Stack: Vite + SvelteKit

## Code

https://github.com/dimfeld/sveltekit-with-svelte-query

**Comment by chbdetta** [comment]
I am having build error with `webpack` after updating to v4. Is this related?
```
Error: ModuleNotFoundError: Module not found: Error: Can't resolve 'util' in '/Users/haydenchen/workspace/thor_next/node_modules/broadcast-channel/src/methods'
```

**Comment by benmccann** [comment]
@chbdetta can you test if the PR fixes it? https://github.com/pubkey/broadcast-channel/pull/691  If it doesn't, can you provide a repository that reproduces it?

**Comment by adam-lynch** [comment]
In my case using Vite, it errors when `nano-time` (imported by `methods/node.js`) tries to call `process.hrtime`. Even if it didn't, it would fail when `fs` is used below that.

@benmccann your PR doesn't solve it for me.

This works for me: import `broadcast-channel/dist/lib/index.es5.js` rather than `broadcast-channel`.

**Comment by benmccann** [comment]
@adam-lynch I tested with SvelteKit which uses Vite. While I did hit issues still, they were in `broadcast-channel` dependencies and caused by a Vite bug that I will work on getting fixed after the PR is checked in. I'd need the PR checked in to really be able to report the issue with a reproduction though

It sounds like your issue on the client-side with Vite? I'm guessing client-side in which case you may need to define `process.browser`:
```
			plugins: [
				replace({
					preventAssignment: true,
					values:{
						'process.browser': true
					}
				})
			]
```

Though I didn't have to do this, but what you're reporting is different than what I'm seeing

**Comment by adam-lynch** [comment]
@benmccann `method-chooser.js` does look for `process.browser` but the `node.js` import is above it

**Comment by benmccann** [comment]
Yeah, but Vite should dead code eliminate it as unused

**Comment by adam-lynch** [comment]
I had set `process.browser`, albeit via:

```
define: {
  'process.browser': true,
}
```

I confirmed it existed but maybe Vite doesn't do the dead-code elimination if it's set this way. I *think* it was loading files in `dist/es` which eventually imports `src/methods/node.js`.

I tried what you have above (I assumed that you're using `@rollup/plugin-replace`) but the dependency won't even load;

- Browser console: `Loading module from “https://.../@fs/.../node_modules/.vite/broadcast-channel_dist_lib_index_es5_js.js?v=3e601c07” was blocked because of a disallowed MIME type (“”)`.
- Terminal: `Internal server error: ENOENT: no such file or directory, open '/.../node_modules/.vite/dep:broadcast-channel_dist_lib_index_es5_js'`

I think I'll give up and go with importing `broadcast-channel/dist/lib/index.es5.js` manually for now since it works.

**Comment by benmccann** [comment]
It's so weird because I'm using Vite and have never seen an error that looks like that. Would you be able to share a repository that reproduces the issue?

**Comment by adam-lynch** [comment]
I can try to create a minimal example from scratch... but heads up I probably don't have time for the next week or so

**Comment by jsprog** [comment]
When testing with `broadcast-channel`, I had to manually hard reload the browser tab to clear the cache and even delete `node-modules/.vite` everytime I made a change to its content.
[https://vitejs.dev/guide/dep-pre-bundling.html#file-system-cache](https://vitejs.dev/guide/dep-pre-bundling.html#file-system-cache)

I managed to `import from 'broadcast-channel/lib'` with success after I followed the recommendation from @adam-lynch, by adding `vite: { define: { 'process.browser': true } }`

But I can't `import from 'broadcast-channel'` directly and I'm receiving this error
> process.hrtime is not a function.

The usage of `process.hrtime` is part of **nano-time** module, and even if you managed to replace both **`const loadNs = process.hrtime();`** and **`let diffNs = process.hrtime(loadNs);`** with **`const loadNS = [1, 1000]`** and **`let diffNS = [2, 2000]`** respectively, you're receive another error which is:

> util.promisify is not a function

What I'm suspecting is that **`dist/es/method-chooser.js`** is choosing methods related to node.js instead of browser, and this is the case when we import from 'broadcast-channel' as a module.

@benmccann, I'm not receiving any error message about `require not defined`, but I managed to face it once during my tests due to caching issues, and the error disappeared after a hard reload.

**Comment by jsprog** [comment]
@benmccann, I tested everything with **vite** and **svelte** and I'm receiving matching results and issues

As an example, just create a project from scratch (vite or sveltekit)

- create a new vite project
- cd to project
- npm install
- npm install broadcast-channel

replace both `vite.config.js` and `App.svelte` with these:

```js
// vite.config.js
import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'

// https://vitejs.dev/config/
export default defineConfig({
  define: { 'process.browser': true },
  plugins: [
    svelte(),
  ]
})
```
```svelte
<!-- App.svelte.js -->
<script>
  import { onMount } from 'svelte'

  import { BroadcastChannel, createLeaderElection } from 'broadcast-channel' // failing
  // import { BroadcastChannel, createLeaderElection } from 'broadcast-channel/dist/lib' // success
  // import { BroadcastChannel, createLeaderElection } from 'broadcast-channel/dist/lib/index.es5' // success

  let is_leader = false
  onMount(() => {
    const channel = new BroadcastChannel('channel');
    const elector = createLeaderElection(channel)
    elector.awaitLeadership().then(() => {
      is_leader = true
      console.log('This tab is now leader.')
    })
  })
</script>

<main>
  <div>Testing with broadcast-channel</div>
  <br>

  <div>is_leader: {is_leader}</div>
</main>
```

**Comment by chbdetta** [comment]
@benmccann For the webpack case, it's the [`mainFields`](https://webpack.js.org/configuration/resolve/#resolvemainfields) config causing the problem. Prioritizing `module` over `browser` can cause webpack to grab the nodejs build.

However, according to https://github.com/webpack/webpack/issues/4674#issuecomment-773040416, the `module` field can have overriding meaning: it can be Node ESM module or Web ESM module. I think to resolve this, they introduce a new [`exports`](https://webpack.js.org/guides/package-exports/) field in package.json, which is currently supported by Node.js, webpack, rollup and others.

**Comment by chbdetta** [comment]
Although the above PR with `exports` field solves the webpack build error, the runtime error of `Uncaught ReferenceError: process is not defined` still persists and it's due to the fact that webpack@5 simply does not define `process.browser` by default. Explicit configuration via [`EnvironmentPlugin`](https://webpack.js.org/plugins/environment-plugin/) or [`DefinePlugin`](https://webpack.js.org/plugins/define-plugin/) is required for such usage.

**Comment by benmccann** [comment]
Ah, I hadn't used Webpack 5 yet and didn't realize that was no longer happening by default. I agree with you that `process.browser` is probably not the best solution given that. We should probably just create two different ES builds - one for the browser and one for node. We should be able to do that using the `exports` field. Thanks for suggesting `exports` as a solution. It's pretty new, so I forgot about it as it's not something I've used a ton. It'll probably depend on our two pending PRs, so maybe we can do it as a follow up to them
